ds_security:
    acl:
        permissions:
            record:             { entity: Ds\Bundle\RecordBundle\Entity\Record, attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
            record_field:       { field:  Ds\Bundle\RecordBundle\Entity\Record.*, attributes: [BROWSE, READ, EDIT] }
