parameters:
    _record: Ds\Bundle\RecordBundle\Entity\Record

ds_security:
    permissions:
        record:               { title: Record,        entity: '%_record%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        record_field:         { title: All Fields,    field:  '%_record%.*',            attributes: [BROWSE, READ, EDIT] }
        record_id:            { title: ID,            field:  '%_record%.id',           attributes: [BROWSE, READ, EDIT] }
        record_uuid:          { title: UUID,          field:  '%_record%.uuid',         attributes: [BROWSE, READ, EDIT] }
        record_created_at:    { title: Created At,    field:  '%_record%.createdAt',    attributes: [BROWSE, READ, EDIT] }
        record_updated_at:    { title: Updated At,    field:  '%_record%.updatedAt',    attributes: [BROWSE, READ, EDIT] }
        record_deleted_at:    { title: Deleted At,    field:  '%_record%.deletedAt',    attributes: [BROWSE, READ, EDIT] }
        record_owner:         { title: Owner,         field:  '%_record%.owner',        attributes: [BROWSE, READ, EDIT] }
        record_owner_uuid:    { title: Owner UUID,    field:  '%_record%.ownerUuid',    attributes: [BROWSE, READ, EDIT] }
        record_identity:      { title: Identity,      field:  '%_record%.identity',     attributes: [BROWSE, READ, EDIT] }
        record_identity_uuid: { title: Identity UUID, field:  '%_record%.identityUuid', attributes: [BROWSE, READ, EDIT] }
        record_title:         { title: Title,         field:  '%_record%.title',        attributes: [BROWSE, READ, EDIT] }
