services:
    ds_record.record.filter:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { uuid: exact }
        tags:
            - { name: api_platform.filter, id: ds_record.record.filter }

    ds_record.association.filter:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { uuid: exact }
        tags:
            - { name: api_platform.filter, id: ds_record.association.filter }
