services:
    ds_record.serializer.context_builder.record:
        decorates: api_platform.serializer.context_builder
        class: Ds\Bundle\RecordBundle\Serializer\ContextBuilder\RecordContextBuilder
        arguments:
            - "@ds_record.serializer.context_builder.record.inner"
            - "@security.authorization_checker"

    ds_record.serializer.context_builder.association:
        decorates: api_platform.serializer.context_builder
        class: Ds\Bundle\RecordBundle\Serializer\ContextBuilder\AssociationContextBuilder
        arguments:
            - "@ds_record.serializer.context_builder.association.inner"
            - "@security.authorization_checker"
