services:
    ds_record.service.record:
        class: Ds\Bundle\RecordBundle\Service\RecordService
        arguments:
            - '@doctrine.orm.entity_manager'
            - Ds\Bundle\RecordBundle\Entity\Record

    ds_record.service.record_association:
        class: Ds\Bundle\RecordBundle\Service\RecordAssociationService

    ds_record.filter.record.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
                id: exact
                uuid: exact
                owner: exact
                ownerUuid: exact
                identity: exact
                identityUuid: exact
        tags:
            - { name: api_platform.filter, id: ds.record.search }

    ds_record.filter.record.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            -
                createdAt: ~
                updatedAt: ~
                deletedAt: ~
        tags:
            - { name: api_platform.filter, id: ds.record.date }

    ds_record.filter.record_association.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
                id: exact
                uuid: exact
                owner: exact
                ownerUuid: exact
                entity: exact
                entityUuid: exact
        tags:
            - { name: api_platform.filter, id: ds.record_association.search }

    ds_record.filter.record_association.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            -
                createdAt: ~
                updatedAt: ~
                deletedAt: ~
        tags:
            - { name: api_platform.filter, id: ds.record_association.date }
