version: '3.1'

services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  redis:
    image: redis:4.0.8-alpine
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - redis_data:/data:rw

  php:
    image: 'digitalstate/records:${IMAGE_TAG}'
    depends_on:
      - database
    command: ['wait-for', 'records_database:${DATABASE_PORT}', '--timeout=60', '--', 'docker-app-start']
    volumes:
      - '${DIRECTORY}:/srv/api-platform'
    links:
      - database:records_database
      - redis:records_redis

  nginx:
    image: nginx:1.11-alpine
    depends_on:
      - php
    environment:
      VIRTUAL_HOST: '${NGINX_VIRTUAL_HOST}'
    volumes:
      - '${DIRECTORY}/docker/nginx/conf.d:/etc/nginx/conf.d:ro'
      - '${DIRECTORY}:/srv/api-platform'
    links:
      - php:records_php

volumes:
  database_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    external:
      name: '${NETWORK}'
