security:
    providers:
        jwt:
            lexik_jwt:
                class: Ds\Bundle\UserBundle\Security\User\User

    role_hierarchy:
        ROLE_ADMIN: ROLE_INDIVIDUAL

    acl:
        connection: default

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern: ^/(records|associations)
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/records, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/associations, roles: IS_AUTHENTICATED_FULLY }
