services:
    app.repository.record:
        class: AppBundle\Repository\RecordRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Record

    app.repository.record_association:
        class: AppBundle\Repository\RecordAssociationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\RecordAssociation
