services:
  app.tenant.loader.access:
    class: AppBundle\Tenant\Loader\AccessLoader
    arguments:
      - '@ds_security.service.access'
      - '@ds_security.service.permission'
    tags:
      - { name: ds_tenant.loader }

  app.tenant.loader.config:
    class: AppBundle\Tenant\Loader\ConfigLoader
    arguments:
      - '@ds_config.service.config'
    tags:
      - { name: ds_tenant.loader }

  app.tenant.unloader.record:
    class: AppBundle\Tenant\Unloader\RecordUnloader
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: ds_tenant.unloader }

  app.tenant.unloader.record_association:
    class: AppBundle\Tenant\Unloader\RecordAssociationUnloader
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: ds_tenant.unloader, priority: -1 }
